[package]
name = "tc"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
authors = ["Antonio Ricciardi <dev.roothunter@gmail.com>"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

bincode = "1.3"
rustc-hash = "2"
priority-queue = "2.1"