[package]
name = "tc"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rustc-hash = "2.0.0"

[dev-dependencies]
log = "0.4"
env_logger = "0.11.5"
chrono = "0.4.38"